Feat iterative match
epiverse-trace/vaccineff pull request #63
Opened 2024-08-05 07:42 UTC by davidsantiagoquevedo

This PR introduces an iterative matching routine to avoid underestimating the VE when removing unvaccinated outcomes whose exposure times do not coincide with their vaccinated pair. Three main functions were added:

1. `iterate_match()`: Handles the main while loop to search for new pairs. It rematches the population separately, first removing vaccinated individuals and then removing unvaccinated individuals. The loop continues until there are no more matches to perform or a certain threshold is reached.
2. `rematch_()`: Controls the re-matching of removed pairs. A `tryCatch` statement is used to handle possible errors.
3. `capture_warnings()`: Captures warning messages to handle tests and to report in the summary of the matching routine.

By introducing these functions, the pipeline of `match_static()` was changed. The iterative match is performed after the initial adjustment. The row `removed` was also deprecated from `match_summary()`.

Necessary tests were built for all functions.

2024-08-09 11:15 UTC, GeraldineGomez requested changes

2024-08-09 11:15 UTC, GeraldineGomez commented on R/coh_match_iterate.R
> +  while ((nrow(adjusted_i) != 0) && (im < thershold)) { #nolint
Removing #nolint comments is necessary for CRAN submission

2024-08-09 11:15 UTC, GeraldineGomez commented on R/handler_warnings.R
> +#' avoiding warnings appearing in the middle of a routine (for instance,
This is useful for 
#' preventing warnings from appearing during routines, such as
#' iterative processes

2024-08-09 11:15 UTC, GeraldineGomez commented on R/handler_warnings.R
> +      invokeRestart("muffleWarning")
Santi, please validate the use of  ` invokeRestart("muffleWarning")`  according to CRAN policy

2024-08-09 11:15 UTC, GeraldineGomez commented on R/handler_warnings.R
> +#' @param warn_env An optional environment to store the warnings.
Specify that the function does not affect the user's environment and explain the usage of `invokeRestart("muffleWarning")`

2024-08-18 11:48 UTC, davidsantiagoquevedo commented on R/coh_match.R
>  #' @param ... Additional arguments passed to other functions.
I included an example using `warnings_log` in the documentation of `match_cohort()`

2024-08-20 10:37 UTC, GeraldineGomez approved these changes

2024-08-20 11:27 UTC, merged